version: "3.9"
services:
  teamcity:
    image: "jetbrains/teamcity-server:2017.1.5"
    volumes:
      - ./teamcity/data:/data/teamcity_server/datadir
      - ./teamcity/logs:/opt/teamcity/logs
    ports:
      - 8111:8111
    links:
      - db
    command: "/run-services.sh"
    depends_on:
      - db

  teamcity-agent-1:
    image: jetbrains/teamcity-agent:2017.1.5
    privileged: true
    volumes:
      - ./agents/agent_1/conf:/data/teamcity_agent/conf
    environment:
      SERVER_URL: "http://teamcity:8111"
      DOCKER_IN_DOCKER: start
    depends_on:
      - teamcity

  db:
    # latest postgres on AWS RDS
    image: "postgres:12.6"
    ports:
      - 8112:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PORT: 5432
      POSTGRES_DB: teamcity
      POSTGRES_USER: teamcity
      POSTGRES_PASSWORD: teamcity
      PGDATA: /var/lib/postgresql/data/pgdata
    # custom config for TC
    command: "postgres -c shared_buffers=512MB -c max_wal_size=1500MB -c synchronous_commit=off -c checkpoint_completion_target=0.9"
